### PR TITLE
⬆ Upgrade constrain for SQLAlchemy = ">=1.4.17,<=1.4.41"

### PR DESCRIPTION
**Pull request by RobertRosca**
SQLAlchemy changes in versions greater than 1.4.35 break relationships and break even the examples in the docs, the latest working version seems to be 1.4.35.

This has been the cause of at least two issues (https://github.com/tiangolo/sqlmodel/issues/255, https://github.com/tiangolo/sqlmodel/issues/315) but probably more.

The breaking change wasn't picked up by dependabot because the current constraint of `<1.5.0` does not register any releases under 1.5.0 as 'new' since the version constraint does not have to be bumped up for it. By limiting it to <**=** dependabot will start bumping up the upper end of the constraints.

PR https://github.com/tiangolo/sqlmodel/pull/322 fixes this with a simple code change but hasn't been merged yet, the constraint range change should still be made so that dependabot will automatically create PRs and run tests on newer versions of SQLAlchemy.

### CODE REVIEW

**Comment by ajlive** [comment]
Since sqlmodel has been broken since, I guess, May (?) with this PR unmerged since May, should I assume sqlmodel is unmaintained? Not a gripe at all, just trying it out and wondering if the project still active.

**Comment by byrman** [comment]
> This has been the cause of at least two issues (https://github.com/tiangolo/sqlmodel/issues/255, https://github.com/tiangolo/sqlmodel/issues/315) but probably more.

Note that https://github.com/tiangolo/sqlmodel/issues/255 was opened on Feb 28, while SQLAlchemy 1.4.36 was released on Apr 6, 2022.

**Comment by RobertRosca** [comment]
> Since sqlmodel has been broken since, I guess, May (?) with this PR unmerged since May, should I assume sqlmodel is unmaintained? Not a gripe at all, just trying it out and wondering if the project still active.

I think @tiangolo is just pretty busy right now. The rate of new issues and PRs is pretty high so it's easy to miss something like this, especially if you're relying on dependabot to test and flag these kind of issues. Changing the constraint from `<` to `<=` should help a bit since it'll bump up the version and run the tests for new SQLAlchemy versions in the future.

**Comment by RobertRosca** [comment]
> > This has been the cause of at least two issues (#255, #315) but probably more.
> 
> Note that #255 was opened on Feb 28, while SQLAlchemy 1.4.36 was released on Apr 6, 2022.

Aha, interesting, to be honest I was lazy and just searched for 1.4.35 and assumed that any issue where people said installing that version fixed the problem was related to this. This comment https://github.com/tiangolo/sqlmodel/issues/255#issuecomment-1151481402 mentioned that pinning the version to `<=1.4.35` fixed the problem so it seemed related, but yeah based on the dates that doesn't make sense :thinking:

**Comment by ajlive** [comment]
Thanks @RobertRosca! Good to know it's still active.

**Comment by cisaacstern** [comment]
+1 for this PR so that, as @RobertRosca observes, dependabot can more easily track this issue.

**Comment by tiangolo** [comment]
Awesome, thank you @RobertRosca! :rocket: 

I upgraded the max version to the current latest, as everything is passing with it. :nerd_face: 

And thanks everyone for the discussion. The underlying issue was solved in https://github.com/tiangolo/sqlmodel/pull/322, and this version pin will prevent it from happening inadvertently.

This will be available in the next version, in the next hours. SQLModel `0.0.7` :rocket:

**Pull request merged**
