### PR TITLE
✨ Allow setting `unique` in `Field()` for a column

### PR DESCRIPTION
**Pull request by raphaelgibson**
Add unique constraint param to Field function to create unique columns.
I have added tests for these modifications.

### CODE REVIEW

**Comment by hvonbargen** [comment]
I think that a column is not the right place for a unique constraint. And there can be more than one unique constraints for a table. The natural representation for a unique constraint is a list of columns. And a unique constraint should have a name.

**Comment by christophelec** [comment]
I think a column can perfectly be the right place for a unique constraint, if the unicity constraint is on one column only.

The possibility to create constraints on multiple columns should of course exist as well, but adding a nameless unique constraint to a single column is a pretty common use case.

And it seems people from postgresql agree : https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS.

**Comment by nuno-andre** [comment]
Hi @christophelec!

I would also set `index` to `False` if `Undefined` (which is the SQLAlchemy's default) so that a `UNIQUE CONSTRAINT` clause be included in the column definition. Otherwise, an index with `unique=True` will be generated.

https://github.com/sqlalchemy/sqlalchemy/blob/a91df497d8d78292b0b5e7f79656b3f82d7de4f7/lib/sqlalchemy/sql/schema.py#L1448-L1509

**Review by chungg — APPROVED** [review]

**Comment by tiangolo** [comment]
Awesome! Thanks for writing thorough tests @raphaelgibson! :rocket: :bow: :cake:

**Pull request merged**
