### PR TITLE
🐛 Fix `Select` and `SelectOfScalar` to inherit cache to avoid warning: `SAWarning: Class SelectOfScalar will not make use of SQL compilation caching`

### PR DESCRIPTION
**Pull request by rabinadk1**
Fixes: #189
Original Solution found in https://github.com/tiangolo/sqlmodel/issues/189#issuecomment-1025190094 from @leynier

### CODE REVIEW

**Comment by leynier** [comment]
Cool 👌🏼

**Comment by carlbordum** [comment]
This patch looks good to me.

**Comment by oldfielj-ansto** [comment]
Noticed this as well, would be nice to get rid of the warning spam.

LGTM

**Review by oldfielj-ansto — APPROVED** [review]

**Review by leynier — APPROVED** [review]

**Comment by tiangolo** [comment]
Awesome! Thanks a lot @rabinadk1 and @leynier for the tip! :cake: :coffee: 

This will be available in SQLModel `0.0.7`, released in the next hours. :tada:

**Pull request merged**
