### PR TITLE
🐛 Fix `AsyncSession` type annotations for `exec()`

### LINKED ISSUE #54: AsyncSession does not play well with typing and autocompletion
# TL;DR: Fix is available here: #58, pls merge.

### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [x] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import asyncio
from typing import Optional

from sqlalchemy.ext.asyncio import create_async_engine
from sqlmodel import Field, SQLModel, select
from sqlmodel.ext.asyncio.session import AsyncSession


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None


async def main() -> None:
    engine = create_async_engine("sqlite+aiosqlite:///database.db")

    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)

    async with AsyncSession(engine) as session:
        session.add(Hero(name="Spider-Boy", secret_name="Pedro Parqueador"))
        await session.commit()

    async with AsyncSession(engine) as session:
        statement = select(Hero).where(Hero.name == "Spider-Boy")
        h = (await session.exec(statement)).first()
        print(h)  # name='Spider-Boy' id=2 age=None secret_name='Pedro Parqueador'


asyncio.run(main())
```

### Description
First of all, props for yet another amazing library!  🎉❤️ 

I didn't dive into source code yet to verify that I'm doing the right thing, but in the runtime the snippet behaves as expected. However that's not the case with static analysis:

- Mypy gives this error:
  ```py
  $ mypy model.py  # Mypy Version: 0.910                                        
  model.py:21: error: Argument 1 to "exec" of "AsyncSession" has incompatible type "SelectOfScalar[Hero]"; expected "Union[Select[<nothing>], Executable[<nothing>]]"
  Found 1 error in 1 file (checked 1 source file)
  ```

- PyCharm fails to derive `session` variable type:
  image
  May be related to [PY-29891](https://youtrack.jetbrains.com/issue/PY-29891)!

- Even when `session` type explicitly stated, PyCharm still struggles to provide same experience as with sync `Session`
  image

I acknowledge that the issue might be caused Typing/MyPy/PyCharm limitations.

I would be happy to work towards fixing the issue in my free time. Ideally, for that I'd want some clarification and thoughts regarding the issue.

### Operating System

macOS 11.4 (20F71)

### SQLModel Version

0.0.4

### Python Version

Python 3.9.6

### Additional Context

- Before running code snipped, you need to `pip install aiosqlite sqlalchemy[asyncio]`
- Mypy Version: `0.910`
- PyCharm Version: `PyCharm 2021.1.3 (Professional Edition) Build #PY-211.7628.24, built on June 30, 2021`

### PR DESCRIPTION
**Pull request by Bobronium**
### `hero.py`:
```py
import asyncio
import inspect
import sys
from contextlib import suppress
from pathlib import Path
from typing import Optional, TYPE_CHECKING

from mypy.main import main as mypy_main
from sqlalchemy.ext.asyncio import create_async_engine
from sqlmodel import Field, SQLModel, select
from sqlmodel.ext.asyncio.session import AsyncSession


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None


async def main() -> None:
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")

    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)

    async with AsyncSession(engine) as session:
        session.add(Hero(name="Spider-Boy", secret_name="Pedro Parqueador"))
        await session.commit()

    async with AsyncSession(engine) as session:
        statement = select(Hero).where(Hero.name == "Spider-Boy")
        reveal_type(session)
        result = await session.exec(statement)
        reveal_type(result)
        h = result.first()
        reveal_type(h)


if not TYPE_CHECKING:

    def reveal_type(obj):
        f_back = inspect.currentframe().f_back
        filename = f_back.f_globals["__file__"]
        with suppress(ValueError):
            filename = Path(filename).relative_to(Path.cwd())
        print(f"{filename}:{f_back.f_lineno}: note: Runtime value is {obj!r}")


print("Running main()")
asyncio.run(main())
print("\nRunning mypy (first run may take some time)")
mypy_main(None, stdout=sys.stdout, stderr=sys.stderr, args=[__file__])
```
### Running on [main](https://github.com/tiangolo/sqlmodel/tree/main)
```py
Running main()
hero.py:33: note: Runtime value is <sqlmodel.ext.asyncio.session.AsyncSession object at 0x10314f9a0>
hero.py:35: note: Runtime value is <sqlalchemy.engine.result.ScalarResult object at 0x10308bdc0>
hero.py:37: note: Runtime value is Hero(age=None, name='Spider-Boy', secret_name='Pedro Parqueador', id=1)

Running mypy (first run may take some time)
hero.py:33: note: Revealed type is 'sqlmodel.ext.asyncio.session.AsyncSession*'
hero.py:34: error: Need type annotation for 'result'
hero.py:34: error: Argument 1 to "exec" of "AsyncSession" has incompatible type "SelectOfScalar[Hero]"; expected "Union[Select[<nothing>], Executable[<nothing>]]"
hero.py:35: note: Revealed type is 'sqlmodel.engine.result.ScalarResult[Any]'
hero.py:37: note: Revealed type is 'Union[Any, None]'
Found 2 errors in 1 file (checked 1 source file)
```
### Running on [Bobronium:AsyncSession_typing_fix](https://github.com/Bobronium/sqlmodel/tree/AsyncSession_typing_fix):
  ```py
  Running main()
  hero.py:43: note: Runtime value is <sqlmodel.ext.asyncio.session.AsyncSession object at 0x102a0f940>
  hero.py:45: note: Runtime value is <sqlalchemy.engine.result.ScalarResult object at 0x1029e9190>
  hero.py:47: note: Runtime value is Hero(name='Spider-Boy', secret_name='Pedro Parqueador', id=1, age=None)

  Running mypy (first run may take some time)
  hero.py:43: note: Revealed type is 'sqlmodel.ext.asyncio.session.AsyncSession*'
  hero.py:45: note: Revealed type is 'sqlmodel.engine.result.ScalarResult*[hero.Hero*]'
  hero.py:47: note: Revealed type is 'Union[hero.Hero*, None]'
  ```
  image

### CODE REVIEW

**Comment by Bobronium** [comment]
@tiangolo, is this PR or #54 going to be addressed?

**Review by priyansh-anand — APPROVED** [review]

**Comment by priyansh-anand** [comment]
Thanks for the feature! Until this PR gets merged, manually patching will work for my workflow.

**Comment by Bobronium** [comment]
@tiangolo, I can try to resolve CI issues and update the branch, but I need a confirmation that you have intention of merging it once issues are resolved and willing to communicate if I'll need any feedback on resolving them. Complete lack of comminucation from your side is frustrating.

I don't want to waste any more time on this PR only to find it in the same condition a year later.

**Comment by maresb** [comment]
Thanks @Bobronium for the fix, I am pip installing your branch instead of v0.0.8. I hope this gets merged soon.

**Comment by diego-escobedo** [comment]
Crazy this has been around since 2021. Awesome work @Bobronium on this.

**Comment by Bobronium** [comment]
@tiangolo, I've fixed CI issue. 

Tests are passing now. 

Please merge.

**Pull request merged**
