### PR TITLE
🐛 Fix Enum handling in SQLAlchemy

### PR DESCRIPTION
**Pull request by chriswhite199**
Addresses issues #96 & #164

### CODE REVIEW

**Comment by chriswhite199** [comment]
This is more-or-less a duplicate of #24, but adds in a test to assert the DDL for postgres and sqlite.

**Comment by carlbordum** [comment]
This is a good patch - hope it gets merged :rocket:

**Comment by StichCode** [comment]
why not merged yet?

**Comment by dane-skipper** [comment]
+1 for merging
@chriswhite199 really small nit, but it may be worth combining the three `sqlalchemy` import statements you have into a single one

**Comment by mattyoungberg** [comment]
Getting the SQLAlchemy native enum supported here is important is making or breaking whether or not I use it in my project (as well as many others, it sounds like)... I'd make a PR myself, but this one is perfectly fine (As well as #24 except this has tests). This might be overkill, but I'm gonna ping all the maintainers because something like this should NOT be left for 6 months without action on a library that's meant to nicely compliment FastAPI:

@tiangolo 
@egrim 
@sobolevn 
@Batalex 
@Lehoczky 
@yaquelinehoyos 
@sebastianmarines 
@robcxyz 
@leynier 
@nomagick 
@hanxiao 

Please, address this. @tiangolo was able to oversee 3 releases of FastAPI last week alone. This library needs more love.

**Comment by Batalex** [comment]
Hi,

>This might be overkill

It is, considering that outside of tiangolo, you pinged one-time contributors, **not** maintainers.

May I suggest that you do the following in order to follow proper OSS etiquette?

- Raise your concerns about the maintenance of the library in a dedicated issue. You have some valid points, but the substance and the form are both equally important when raising such concerns.
- Ease the burden of maintenance. If you feel like the PR is good, your code review, or you testing the branch in a toy project will be greatly appreciated by the maintainer(s).

**Comment by antont** [comment]
>  making or breaking whether or not I use it in my project (as well as many others, it sounds like)... I'd make a PR myself

You can also just merge the PR to your branch. That's what we do to use SQLModel, just merge PRs from here to our fork and install that in our dev envs and deployment. These changes are not so big, and if get synched to main later and there's more work there, I don't see a problem really.

**Comment by mattyoungberg** [comment]
@Batalex, my apologies for pinging contributors.

> Raise your concerns about the maintenance of the library in a dedicated issue. You have some valid points, but the substance and the form are equally important when raising such concerns.

I mean, I COULD, but just a scan of the last thirty days of issues shows barely, if any, maintainer activity. Raising an issue might be "form" but it gets the library nowhere if the issues aren't being engaged with in the first place. Pinging all maintainers is kind of a last resort to get some traction before I consider this library deadlocked from lack of maintenance. 

Heck, traction could be adding some maintainers that DO have capacity to work on this library; I'm certainly not faulting maintainers for having a life. But spending a half hour to message some people and see if they want to be maintainers could go a long ways for the 142 issues and 71 PRs that are currently open. It's only going to snowball.

> Ease the burden of maintenance. If you feel like the PR is good, your code review, or you testing the branch in a toy project will be greatly appreciated by the maintainer(s).

This is a good suggestion, and I'll remember it for the future. I'm going to be using the content of these commits anyway in a forked version of this library, but I wish I didn't have to. I'll report back how well it works.

@antont 

> You can also just merge the PR to your fork. That's what we do to use SQLModel, just merge PRs from here to our organizational fork and install that in our dev envs and deployment.

My previous comment reveals that this was my plan because I wasn't expecting a resolution right away, but it does mean another repository gets added to my company's VCS, which isn't optimal. But alas, I don't think I have another option.

I'm more frustrated with the fact that this library was released three times in a spurt in August, then twice in a spurt in December; there has never been a steady cadence of releases or of merging of good PRs. This library gets advertised as a great compliment to FastAPI and has great docs that suggests its a polished project (because @tiangolo is good at that), only to learn that it's not getting any kind of TLC at all. 

The SQLAlchemy native enum has existed since version 1.1 of SQLAlchemy in 2016, which means that when SQLModel was built in 2021, there were things that were missed. Naturally, that's the course of software; you get something out first and then firm things up over time. But to release and not put infrastructure in place to allow those improvements to happen is frustrating to a developer like me who sees potential in this library.

**Comment by mattyoungberg** [comment]
Third PR regarding this is #197

**Comment by tiangolo** [comment]
Awesome, thank you @chriswhite199! In particular, thanks for writing thorough tests! :bow: 

Thanks everyone for the discussion here. :coffee: 

If any of you wants to help maintain SQLModel, the best help I can get is helping others with their questions in their issues. That's what really takes most of the time. Thanks! :cake:

**Pull request merged**
