### PR TITLE
🐛 Fix SQLAlchemy version 1.4.36 breaks SQLModel relationships (#315)

### PR DESCRIPTION
**Pull request by byrman**

### CODE REVIEW

**Review by jossefaz — COMMENTED** [review]
Can we add unit tests ?

**Comment by byrman** [comment]
> Can we add unit tests ?

What would be a good test? I don't know how to write tests for different SA versions.

**Comment by antont** [comment]
I guess just a test for relationships would work, then it breaks if the SA version is not compatible, and succeeds when yes.

**Comment by antont** [comment]
> OK, but there are plenty of those already. It would be nice if we could prove that it works for both 1.4.36 and older versions of SQLAlchemy.

Right - apparently tests just have not been run in Github Actions in 16d so the breakage does not show.

I don't think a test in itself can define the lib version but that would require something more, maybe like a branch where a different SA version is pinned.

**Comment by mkarbo** [comment]
Running tests without the fix results in broken tests, running with fix all tests pass. You can run them locally to verify

**Review by andy-takker — APPROVED** [review]

**Comment by lonelyteapot** [comment]
Any updates on when this will be merged?

**Comment by berendt** [comment]
@tiangolo Can you take a look at this, please? It is nasty that you have to pin the version of sqlalchemy at the moment. It would be nice if you could make a release after the merge so that the current version of sqlalchemy can be used again.

**Comment by leynier** [comment]
In this PR (https://github.com/leynier/sqlmodel/pull/37) pointing to a fork, you can see that the tests are successful. I think that It is not necessary to add extra tests for this PR because the existing tests validate the change since without the change of this PR the tests fail.

**Review by Karam19925 — APPROVED** [review]
> #322 

> #315 
fix

**Review by CWKevo — APPROVED** [review]

**Comment by tiangolo** [comment]
Awesome, thank you @byrman! :bow: :rocket: 

And thanks everyone for the discussion.

This will be available in the next version, in the next hours. :tada:

**Pull request merged**
