### PR TITLE
testing pydantic v1.10.0a2

### PR DESCRIPTION
**Pull request by samuelcolvin**
### TO NOT MERGE

This is pull request is just to test pydantic v1.10, see https://github.com/pydantic/pydantic/discussions/4359

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi, please can you kick off tests so I can check if v1.10 will break anything.

**Comment by byrman** [comment]
Be aware of https://github.com/tiangolo/sqlmodel/issues/315. This might also cause some tests to fail.

**Comment by samuelcolvin** [comment]
> Be aware of #315. This might also cause some tests to fail.

Oh, thank you so much, I think that's what I was looking for.

**Comment by samuelcolvin** [comment]
apart from the problems with black and sqlalchemy, this seems to be working.

it would appear that sqlmodel is compatible with pydantic v.10 👍 .

Thanks both for your help.

**Pull request closed without merging**
